### ISSUE TITLE
Access role Reader handled differently

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TWI-dashboard#27] opened 2017-08-21 07:35 UTC
NB: Not sure whether this is the right collection to put this issue to, so please assign to other repos as necessary!

Detailed description:
When accessing a collection with user right Reader from the Dashboard (https://transkribus.eu/readTest/dashboard), the following error message is displayed and access is denied:

![2017-08-21_webui_readeraccessfromdashboardlisting](https://user-images.githubusercontent.com/17451573/29508304-5358879a-8654-11e7-851a-44b016ab94ed.PNG)
![2017-08-21_webui_readeraccessfromdashboardfail](https://user-images.githubusercontent.com/17451573/29508307-5ce153b4-8654-11e7-9699-247cde7c7e4f.PNG)

Access is granted to the collection going a different route through using "MyCollections" (https://transkribus.eu/readTest/library/):

![2017-08-21_webui_readeraccessfrommycollectionsok](https://user-images.githubusercontent.com/17451573/29508314-62df98ac-8654-11e7-9142-1077745c3590.PNG)

**Comment by cziaarm** [comment] 2017-09-29 09:36
closed as duplicate of... Transkribus/TWI-mc#47

**Closed as completed by cziaarm** 2017-09-29 09:36 UTC
Labels: duplicate
